### ISSUE TITLE
To: Portable DeltaChat 0.999.1.exe, Win10

### ISSUE THREAD

**Issue by tdev100** [deltachat/deltachat-desktop#1478]
* Its still not a real portable.  The exe runs under User/AppData/Local  instead of my created folder.
  And maybe some more things stored/running somewhere else.
  [* old data in registry, and appdata]
* if possible let me set settings first [and backup], than connect
* when connection failed on startup, all entered connection data is gone

**Comment by r10s** [comment]
there is already 1.0.0, however, not sure if a portable app is a supported use case for now. iirc, as there are more important issues, eg., getting the app to the stores, this was delayed a bit.

**Comment by Jikstra** [comment]
> Its still not a real portable. The exe runs under User/AppData/Local instead of my created folder. And maybe some more things stored/running somewhere else. [* old data in registry, and appdata]


@tdev100 it should create the config folder in the same folder where the .exe lays. At least I fixed this at some point. Probably there's more stuff that is getting created in User/AppData/Local, can you tell me what it is? 

> if possible let me set settings first [and backup], than connect

What do you mean? You can import a backup on the first screen and also enter account data.

> when connection failed on startup, all entered connection data is gone

Can't reproduce on 1.0.0. Can you test 1.0.0?

**Comment by tdev100** [comment]
a) I could not find a portable 1.0.0?  On your main site (https://delta.chat) I get still 0.999.1 for download. Even for the normal desktop app it is shown 0.999.1.  And under preview builds I also cant determine what is 1.0.0.

b) settings:  I have meant the initial(!) setting,  so no backup available available and if data is lost on 
   failure,  I have to enter again (and again).
    
   But the main reason to allow skip initial (login) settings is (aside a possible backup): 
   I want first see/set all the settings (or know what DeltaChat are trying to do) before connecting 
   to the mail-servers and IMAP does something unwanted at my email-providers folder server 
   structures. I dont want/need unforeseen changes from external mail clients.

**Comment by Jikstra** [comment]
> I could not find a portable 1.0.0? On your main site (https://delta.chat) I get still 0.999.1 for download. Even for the normal desktop app it is shown 0.999.1. And under preview builds I also cant determine what is 1.0.0.

1.0.0 had a serious bug which is the reason why we took it down. I will release a new version the next days.

> b) settings: I have meant the initial(!) setting, so no backup available available and if data is lost on failure, I have to enter again (and again).

This seems like another issue and not related to the portable build. Can you open a seperate issue for it? Also if it's a feature request, please use the forum for this :)

**Comment by Jikstra** [comment]
@tdev100 can you try out v1.1.1 again? https://download.delta.chat/desktop/v1.1.1/DeltaChat%201.1.1.exe

**Comment by tdev100** [comment]
I tried v1.2.0 on a fresh Win10 install. Unfortunately, still not a portable. Mostly all is stored under AppData. I suggest to make use of  https://portableapps.com/development tools. 
The side effect: It could reach quite a  lot of other users not knwoing about deltachat using this platform and would also be a further additional standalone messenger feature. 

[Future: For even more spread, I would also suggest an Opera plugin (like Whatsapp/Telegram/Facebook have already in the sidebar. This would maybe than also directly available in other Chrome based browsers).]

**Comment by Simon-Laux** [comment]
you can try making an opera plugin, but in our evaluation/research browsers were not technically ready for an deltachat plugin (atleast for a full deltachat plugin including the core of deltachat, because that needs Raw TCP Sockets, Webassembly and threading support in webassembly, not to mention the core needs to be left run in the background to give notifications as we don#t have a central server like WhatsApp, Telegram and Facebook do).

**Comment by Simon-Laux** [comment]
This issue is already laying around for too long let's make a new one: https://github.com/deltachat/deltachat-desktop/issues/1907
